# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow0(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(488, 563)
        MainWindow.setStyleSheet("background-color: rgb(218,165,32)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 40, 341, 101))
        self.label.setStyleSheet("font: 28pt \"微软雅黑\";\n"
"color: rgb(0, 0, 0);\n"
"\n"
"")
        self.label.setObjectName("label")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(50, 150, 371, 411))
        self.label_11.setStyleSheet("image:url(1/白框区域.png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(80, 260, 321, 1))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 200, 71, 61))
        self.label_2.setStyleSheet("image: url(1/224用户.png);\n"
"background-color: transparent;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 210, 131, 41))
        self.label_3.setStyleSheet("background-color: transparent;\n"
"font: 90 18pt \"Arial\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(130, 310, 271, 41))
        self.lineEdit.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 310, 31, 31))
        self.label_5.setStyleSheet("image: url(1/person.png);\n"
"background-color: transparent;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(80, 410, 31, 31))
        self.label_7.setStyleSheet("image: url(1/密码.png);\n"
"background-color: transparent;")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 400, 271, 41))
        self.lineEdit_2.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(120, 480, 121, 41))
        self.pushButton.setStyleSheet("font: 75 18pt \"Arial\";\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(270, 480, 111, 41))
        self.pushButton_6.setStyleSheet("font: 75 18pt \"Arial\";\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_11.raise_()
        self.line_2.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEdit.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.lineEdit_2.raise_()
        self.pushButton.raise_()
        self.pushButton_6.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "植物识别系统"))
        self.label_3.setText(_translate("MainWindow", "用户登录"))
        self.pushButton.setText(_translate("MainWindow", "登   录"))
        self.pushButton_6.setText(_translate("MainWindow", "注册"))

