# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(617, 455)
        MainWindow.setStyleSheet("")
        MainWindow.setStyleSheet("background-color: rgb(218,165,32)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(130, 20, 371, 411))
        self.label_11.setStyleSheet("image:url(1/白框区域.png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(160, 130, 321, 1))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 60, 71, 61))
        self.label_2.setStyleSheet("image: url(1/224用户.png);\n"
                                   "background-color: transparent;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 70, 171, 41))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "font: 90 18pt \"Arial\";\n"
                                   "")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(210, 140, 271, 41))
        self.lineEdit.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 150, 31, 31))
        self.label_5.setStyleSheet("image: url(1/person.png);\n"
                                   "background-color: transparent;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(160, 220, 31, 31))
        self.label_7.setStyleSheet("image: url(1/密码.png);\n"
                                   "background-color: transparent;")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 210, 271, 41))
        self.lineEdit_2.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 340, 241, 41))
        self.pushButton.setStyleSheet("font: 75 18pt \"Arial\";\n"
                                      "")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 400, 61, 41))
        self.pushButton_2.setStyleSheet("image: url(1/首页.png);\n"
                                        "background-color: transparent;\n"
                                        "")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(210, 280, 271, 41))
        self.lineEdit_3.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(160, 290, 31, 31))
        self.label_8.setStyleSheet("image: url(1/密码.png);\n"
                                   "background-color: transparent;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-50, 40, 681, 461))
        self.label_4.setStyleSheet("image: url(1/back.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.label_11.raise_()
        self.line_2.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEdit.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.lineEdit_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.lineEdit_3.raise_()
        self.label_8.raise_()

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        import csv
        self.name_list = []

        self.data = []
        # with open('information.csv', 'a', encoding='utf-8', newline='') as fp:
        #     # 写
        #     writer = csv.DictWriter(fp, header)
        #     # 将数据写入
        #     writer.writerows(self.data)

        with open('information.csv', encoding='utf-8')as fp:
            reader = csv.DictReader(fp)
            for i in reader:
                print(i['name'], i['password'])
                self.name_list.append(i['name'])

        self.pushButton.clicked.connect(self.zhuce)

    def zhuce(self):
        new_name = self.lineEdit.text()
        new_password = self.lineEdit_2.text()
        new_password_3 = self.lineEdit_3.text()
        if new_name not in self.name_list:
            if new_password == new_password_3:
                self.data.append({new_name: new_password})
                import csv
                header = ['name', 'password']
                with open('information.csv', 'a', encoding='utf-8', newline='') as fp:
                    writer = csv.writer(fp, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
                    # 将数据写入
                    writer.writerow([new_name, new_password])
                msg1 = QtWidgets.QMessageBox.information(None, 'warning', "新用户注册成功", buttons=QtWidgets.QMessageBox.Ok)
                self.lineEdit.setText('')
                self.lineEdit_2.setText('')
                self.lineEdit_3.setText('')
            else:
                msg2 = QtWidgets.QMessageBox.information(None, 'warning', "两次密码输入不同", buttons=QtWidgets.QMessageBox.Ok)
                self.lineEdit_2.setText('')
                self.lineEdit_3.setText('')
        else:
            # msg = QtWidgets.QMessageBox.warning(self, 'warning', "该用户已存在请重新输入",
            #                                     buttons=QtWidgets.QMessageBox.Ok)
            eply = QtWidgets.QMessageBox.information(None, '提示', '该用户已存在请重新输入!', buttons=QtWidgets.QMessageBox.Ok)
            self.lineEdit.setText('')
            self.lineEdit_2.setText('')
            self.lineEdit_3.setText('')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "新用户注册"))
        self.pushButton.setText(_translate("MainWindow", "注册"))

