# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from plant_data import plant_inf
from plant_name import name_list
import cv2
import numpy as np
import os

class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 570)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 861, 621))
        self.label.setStyleSheet("background-color: rgb(218, 165, 32);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, 20, 241, 51))
        self.label_2.setStyleSheet("font: 75 20pt \"微软雅黑\";")
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(140, 100, 161, 31))
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 111, 21))
        self.label_3.setStyleSheet("font: 75 12pt \"微软雅黑\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 180, 361, 311))
        self.label_4.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(490, 190, 111, 21))
        self.label_5.setStyleSheet("font: 75 12pt \"微软雅黑\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(540, 230, 181, 41))
        self.label_6.setStyleSheet("font: 75 16pt \"微软雅黑\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(490, 300, 301, 191))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        #print(plant_inf.keys())
        self.comboBox.addItems(plant_inf.keys())
        self.comboBox.currentIndexChanged.connect(self.change)
        self.change()

    def change(self):
        name=self.comboBox.currentText()
        self.label_6.setText(name)
        self.textEdit.setText(plant_inf[name])
        path=''
        if name=='萼距花':
            path='all_data/eju/微信图片_20240418153922.jpg'
        elif name=='蒲儿根':
            path = 'all_data/puergen/微信图片_20240418234953.jpg'
        elif name=='月季花':
            path = 'all_data/yuejihua/微信图片_20240418153920.jpg'
        elif name=='朱顶红':
            path = 'all_data/zhudinghong/微信图片_20240418153921.jpg'
        else:
            index=name_list.index(name)
            #print(index)
            pic_path=[i for i in os.listdir('all_data/plant_{}'.format(str(index)))][0]
            path='all_data/plant_{}/{}'.format(str(index),pic_path)

        img = cv2.imdecode(np.fromfile(path, dtype=np.uint8), -1)
        small_img = cv2.resize(img, (361, 311))
        cv2.imwrite('resize_show.png',small_img)
        self.label_4.setStyleSheet("image: url(./resize_show.png)")




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "植物类目信息"))
        self.label_3.setText(_translate("MainWindow", "类别选择："))
        self.label_5.setText(_translate("MainWindow", "名称："))
        self.label_6.setText(_translate("MainWindow", "名称："))
if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())