# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import cv2
import numpy as np
from plant_data import plant_inf

class Ui_MainWindow3(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 570)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 861, 621))
        self.label.setStyleSheet("background-color: rgb(218, 165, 32);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 20, 291, 51))
        self.label_2.setStyleSheet("font: 75 20pt \"微软雅黑\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 100, 111, 21))
        self.label_3.setStyleSheet("font: 75 12pt \"微软雅黑\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 160, 361, 311))
        self.label_4.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(490, 170, 111, 21))
        self.label_5.setStyleSheet("font: 75 12pt \"微软雅黑\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(600, 170, 181, 51))
        self.label_6.setStyleSheet("font: 75 12pt \"微软雅黑\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(490, 280, 301, 191))
        self.textEdit.setObjectName("textEdit")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(160, 100, 111, 31))
        self.label_7.setStyleSheet("font: 75 12pt \"微软雅黑\";")
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(680, 490, 101, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(490, 230, 111, 21))
        self.label_8.setStyleSheet("font: 75 12pt \"微软雅黑\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(600, 220, 181, 41))
        self.label_9.setStyleSheet("font: 75 8pt \"微软雅黑\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        with open('name.txt','r')as fb:
            name=fb.readline()
        self.label_7.setText(name)

        with open('users/{}.txt'.format(name), 'r', encoding='gbk')as fb:
            self.data = fb.readlines()
        first_data = self.data[0].split('+')

        img = cv2.imdecode(np.fromfile(first_data[0], dtype=np.uint8), -1)
        input_img = cv2.resize(img, (361, 311))
        cv2.imwrite('resize_img.png', input_img)
        self.label_4.setStyleSheet("image: url(./resize_img.png)")
        self.label_9.setText(first_data[1])
        self.label_6.setText(first_data[2])
        self.textEdit.setText(plant_inf[first_data[2][:-1]])
        self.num = 0

        self.pushButton.clicked.connect(self.next_data)

    def next_data(self):
        self.num += 1
        if self.num == len(self.data):
            self.num = 0
        first_data = self.data[self.num].split('+')

        img = cv2.imdecode(np.fromfile(first_data[0], dtype=np.uint8), -1)
        input_img = cv2.resize(img, (361, 311))
        cv2.imwrite('resize_img.png', input_img)
        self.label_4.setStyleSheet("image: url(./resize_img.png)")
        self.label_9.setText(first_data[1])
        self.label_6.setText(first_data[2])
        self.textEdit.setText(plant_inf[first_data[2][:-1]])

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "用户历史记录信息"))
        self.label_3.setText(_translate("MainWindow", "用户名："))
        self.label_5.setText(_translate("MainWindow", "名称："))
        self.label_6.setText(_translate("MainWindow", "名称："))
        self.label_7.setText(_translate("MainWindow", "用户名："))
        self.pushButton.setText(_translate("MainWindow", "下一张"))
        self.label_8.setText(_translate("MainWindow", "检测时间："))
        self.label_9.setText(_translate("MainWindow", "名称："))
if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow3()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
